#cloud-config
yum_repos:
  puppet5:
    baseurl: http://yum.puppetlabs.com/puppet5/fedora/26/$basearch
    enabled: true
    gpgcheck: true
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-puppet5
    name: Puppet 5 Repository fedora 26 - $basearch
packages:
 - git
 - dnf-plugins-core
 - puppet-agent
package_upgrade: true
final_message: "The system is up after $UPTIME seconds."